- lib/habilitations/strategies/email/pin-code-template.js
Le code d'authentification n'arrive jamais dans le template de l'email envoyé aux communes à cause d'une erreur de nommage.
> Correction du code d'authentification dans l'email

- lib/habilitations/model.js
- lib/habilitations/routes.js
- lib/habilitations/strategies/email.js
- méthode `getCommuneEmail` de `email.js`, utilisé dans `model.js`
- méthodes `decreasesRemainingAttempts` et `rejectHabilitation` de `model.js`, utilisé dans `email.js`
La dépendance circulaire est résolue en déplaçant la méthode `getCommuneEmail` et le code la concernant directement dans `model.js`, sans endroit où cette méthode est utilisée aujourd'hui.
Dans le cas où `!validated` alors la méthode `send` était appelé deux fois. Un `return` a été ajouté afin de stopper l'exécution du code.
> Corrections du processus d'habilitation

- lib/habilitations/__tests__/routes.js
- lib/habilitations/routes.js
Corrige le terme français "authentification" en français par "authentication" dans les routes.
> Corrige le terme "authentication"

- lib/habilitations/strategies/email/index.js
Actuellement la propriété `remainingAttempts` n'est pas renvoyée par la méthode `pinCodeValidation` hors cette information peut être utile pour suivre plus facilement le nombre de tentative restante.
Cette PR ajoute le champ `remainingAttempts` dans le réponse de la méthode `pinCodeValidation` dans les cas où le code n'est pas valide et que `remainingAttempts` est supérieur à 0.
> Ajout du nombre de tentative restante lors de la validation du code

- lib/habilitations/routes.js
Oubli lors de #14, le champ `remainingAttempts ` n'est pas envoyé dans la réponse de l'API…
> Envoi le champ `remainingAttempts` 

- lib/revisions/validate-bal.js
- package.json
- scripts/revalidate-revisions.js
- yarn.lock
Mise à jour de @ban-team/validateur-bal de la version `2.6.0` à `2.8.0`.
Voir les détails de cette version 
https://github.com/BaseAdresseNationale/validateur-bal/releases/tag/v2.8.0
`@etalab/bal` est remplacé par `@ban-team/validateur-bal` (nouveau nom de la dépendance).
> Mise à jour de @ban-team/validateur-bal

- lib/revisions/model.js
- Route concernée : `GET /current-revisions`
- Modification de la fonction `getCurrentRevisions` 
retourne : 
```json
[
{
"_id": "ObjectId",
"codeCommune": "string",
"client": {
"id": "string",
"nom": "string"
},
"publishedAt": "Date"
},
{
"..."
},
]
```
> Expose les propriétés client.id et client.nom de la liste des révisions en cours

- lib/chefs-de-file/__tests__/model.js
- lib/chefs-de-file/__tests__/routes.js
- lib/chefs-de-file/model.js
- lib/chefs-de-file/routes.js
- lib/util/cog.js
- lib/util/payload.js
- server.js
Cette PR prépare la migration du fichier `client.yml` sur mongodb en ajoutant un modèle `ChefDeFile` qui sera lié au prochain modèle `Client`.
```
{
_id: '7n51dae287088f21afd07c580',
nom: 'Nom du chef de file',
email: 'chefdefile@email.fr',
perimetre: ['epci-246800726', 'departement-14', 'commune-27115'],
signataireCharte: true,
_createdAt: '1970-01-01',
_updatedAt: '1970-01-01',
}
```
> Toutes les routes nécéssitent une authentification administrateur
**`/chefs-de-file`**
- Créer un chef de file : `POST /chefs-de-file/`
- Récupérer un chef de file : `GET /chefs-de-file/:chefDeFileId`
- Modifier un chef de file : `PUT /chefs-de-file/:chefDeFileId`
-----
Cette PR est issue d'un découpage de #39 afin de faciliter la revue et l'intégration.
> Ajout du modèle ChefDeFile

- lib/util/raw-body-parser.js
La limite actuelle de `10mb` bloque actuellement les plus grosses communes. Cette PR augmente cette taille limite à `50mb`.
> Augmente la taille autorisé des fichiers à 50mb

- lib/revisions/model.js
- lib/revisions/routes.js
- lib/util/mongo.js
Créer une nouvelle route de l'API en PUT permettant de délivrer un fichier de type json permettant de préciser les suppressions de cette révision (count des idsupprimés et détail des id supprimés). voir l'issue #30 pour le détail
Fix #30
> PROTO ID:Exploiter un fichier des evènements fournis #30

- lib/revisions/__tests__/integration.js
- lib/revisions/routes.js
Lors de la [migration des clients en BDD](https://github.com/BaseAdresseNationale/api-depot/pull/48), les informations publiques du client ont oublié d'être ajoutées à la réponse.
> Ajout des informations publiques du client sur la récupération de la révision courante

- package.json
- yarn.lock
Mise à jour de `@etalab/decoupage-administratif v3.0.0` pour la mise à jour du COG 2023.
> Mise à jour COG 2023

- lib/revisions/__tests__/model.js
- lib/revisions/model.js
- lib/stats/__tests__/routes.js
- lib/stats/__tests__/service.js
- lib/stats/routes.js
- lib/stats/service.js
- lib/util/__tests__/date.js
- lib/util/date.js
- server.js
BalAdmin a besoin d'afficher des stats sur la home, il y a donc besoin d'ajouter des routes sur l'api-depot
Route `stats/creation-evolution?from&to`
Description: Retourne le nombre cumulé de première révision de BAL publiée pour chaque jours entre 'from' et 'to' inclus
Query : `stats/creation-evolution?from=2023-03-12&to=2023-03-28`
Réponse : 
```JSON
[
{ 
"date": "2023-03-12",
"totalCreations": 1000
},
{
"date": "2023-03-28",
"totalCreations": 1010
}
]
```
Route `stats/publications?from&to`
Description: Retourne les BAL publiées pour chaque jours entre 'from' et 'to' inclus
Query : 
`stats/publications?from=2023-03-12&to=2023-03-28`
Réponse : 
```JSON
[
{ 
"date": "2023-03-12",
"publishedBAL": [
{ 
"codeCommune": "37003",
"numPublications": 3
}
]
}
]
```
> Nouvelle routes de stats pour dashboard BalAdmin

- lib/revisions/model.js
- lib/revisions/routes.js
Des problèmes de performance ont été constatés sur la `/current-revisions` depuis la migration des clients de dépôt. 
C'est dû à traitement des clients des révisions très peu optimisé.
Cette PR ajoute la méthode `expandWithClients` qui permet de traiter tous les clients en même temps plutôt de gérer les clients révision par révision.
> Correction des performances de la route /current-revisions

- lib/habilitations/model.js
- lib/util/sendmail.js
Les appels vers les briques BAL sont aujourd'hui redirigés de https://plateforme.adresse.data.gouv.fr/ vers https://plateforme-bal.adresse.data.gouv.fr/.
Cette PR met à jour les variables d'environnement et les URL de fallback pour pointer directement vers la nouvelle URL https://plateforme-bal.adresse.data.gouv.fr/
> Mise à jour des URL vers plateforme-bal

- lib/util/sendmail.js
Le tag `$$API_URL$$` n'était pas remplacer lors de la création du template pour les mail de l'api-depot.
Utiliser la fonctionnalité template de lodash pour remplacer les nouveau tag `apiUrl` par la var env `API_DEPOT_URL`
> Email bien replace le tag Url Api

- lib/clients/routes.js
https://github.com/BaseAdresseNationale/bal-admin/issues/18
Ne plus omettre le champ `token` d'un client sur la route `client/:clientId`
> Delete filterSensitiveFields to route /clients/:clientId

- .env.sample
- lib/files/s3.service.js
- lib/revisions/__tests__/integration.js
- lib/revisions/__tests__/model.js
- lib/revisions/model.js
- lib/revisions/routes.js
- migrations/migration-files-to-s3-storage.js
- package.json
- yarn.lock
Les fichiers CSV des BAL sont actuellement stockés dans MongoDB, ce qui représente 99% du volume de la base de données.
Nous souhaitons externaliser ce stockage vers un stockage S3 hébergé chez OVH pour que Mongo occupe moins de ressources sur le serveur et accélérer les backups.
Cette migration se fera en trois étapes :
- Faire cohabiter le stockage S3 et le stockage dans MongoDB (plus une migration des fichiers déjà existants vers S3). Si le serveur ne trouve pas un fichier demandé dans le stockage S3, il renverra le fichier stocké en base (fonctionnement actuel)
- Une fois que le système fonctionne bien (monitoring via Datadog), nous arrêtons d'inscrire les nouveaux fichiers dans la base de données.
- A terme nous souhaitons supprimer la propriété "data" contenant le fichier de la …
> Migration des fichiers CSV vers un stockage S3

- lib/revisions/__tests__/model.js
- lib/revisions/model.js
- lib/revisions/routes.js
La route `communes/:codeCommune/revisions` ne renvoie que les revisions published
Nouvelle Route `communes/:codeCommune/revisions/all` qui renvoie toutes revisions d'une commune
> Route all revisions by commune

- lib/emails/__tests__/notify-partners-on-force-publish.js
- lib/emails/notify-partners-on-force-publish.js
- lib/revisions/__tests__/notify-partners.js
- lib/revisions/model.js
- lib/revisions/notify-partners.js
Afin de permettre au partenaire d'être informé lorsqu'une commune reprend la main sur son adressage, nous voulons les notifier par email lors de la publication de la révision.
> feat: notify partners when force publish

- lib/habilitations/build-rne/index.js
La commande `yarn habilitations:build-rne` car le csv du dataset a changé ses séparateur par des virgules
Changement des séparateur de la lib csvParse
Lancer la commande sur le serveur une fois mergé
> fix: build-rne

- .env.sample
- README.md
- lib/habilitations/model.js
L'api des établissement public est souvent en retard avec l'annuaire public et certaines mairies ne peuvent pas s'habilité
La nouvelle api-annuaire est a jour avec l'annuraire public
Rempacement de l'api des etablissement public avec la nouvelle api de l'annuaire public pour récupérer les mails des marie
> Migration: new api annuaire

- lib/habilitations/__tests__/routes.js
- lib/habilitations/routes.js
- Ajout d'une route /habiliations/:id/validate (protégé par ensureAdmin) pour valider avec le type `interne` les habilitations
> feat: add route admin validate habilitation

- src/modules/habilitation/habilitation.module.ts
- src/modules/revision/revision.module.ts
Mattermost : https://mattermost.incubateur.net/betagouv/pl/iy7nwfkmo3domc91d4jf41smfy
Problème : Quand on applique un middleware sur une route en particulier, il ne fonctionne qu'avec la méthode http attendue par le controller. Le souci c'est que pour les methodes HEAD et OPTIONS, le middleware ne s'applique pas et le serveur renvoie une 500.
=> Appliquer les middleware pour toutes les méthodes HTTP
> fix: make middleware work with all http methods

- src/modules/api_annuaire/api_annuaire.service.ts
- src/modules/api_annuaire/api_annuaire.spec.ts
- src/modules/habilitation/dto/send_code_pin.dto.ts
- src/modules/habilitation/habilitation.controller.ts
- src/modules/habilitation/habilitation.service.ts
- src/modules/habilitation/habilitation.spec.ts
- Ne plus remplir emailCommune a la création de l'habilitation
- Recevoir le mail du destinataire dans la route `/habilitation/send-code-pin`
- Vérifier que le mail appartient bien a la commune
- Set le communeMail lorsque le mail est envoyé
> feat:  add mail in route send code pin

- src/lib/class/pipes/validation_cog.pipe.ts
- src/modules/revision/revision.controller.ts
- src/modules/revision/revision.service.ts
- src/modules/revision/revision.spec.ts
- AJout d'un query params sur la route /current-revisions pour récupérer seulement certaine commune si on ne veut pas les révision courante des 36000 communes
> feat: add query params codeCommune to route /current-revision
